const sections = [
  { id:'cranial', icon:'◉', title:'Cranial nerves', groups:[
    {title:'Vision and eye movements', fields:[
      ['VA','text'], ['Visual fields','visual'], ['Pupils','otherChoice',['Equal and reactive','Other']], ['Eye movements','otherChoice',['Full','Other']], ['Pursuits','otherChoice',['Normal','Other']], ['Saccades','otherChoice',['Normal','Other']], ['Nystagmus','otherChoice',['No','Other']]
    ]},
    {title:'Face, bulbar and speech', fields:[
      ['Facial sensation','otherChoice',['Normal','Other']], ['Facial movement','otherChoice',['Normal','Other']], ['Hearing','otherChoice',['Normal','Other']], ['Palate','otherChoice',['Midline','Other']], ['Tongue','choice',['Midline','Wasting','Fasciculations','Other']], ['Dysarthria','otherChoice',['No','Other']], ['Aphasia','otherChoice',['No','Other']]
    ]}
  ]},
  { id:'motor', icon:'↗', title:'Motor', groups:[
    {title:'Bulk, tone and drift', fields:[
      ['Bulk UL','text'], ['Bulk LL','text'], ['Tone arms','choice',['Normal','Increased R','Increased L','Reduced R','Reduced L','Other']], ['Tone legs','choice',['Normal','Increased R','Increased L','Reduced R','Reduced L','Other']], ['Pronator drift','choice',['None','Right','Left','Other']], ['Fasciculations','otherChoice',['No','Other']]
    ]},
    {title:'Power (MRC)', fields:[['Power','power']]}
  ]},
  { id:'reflexes', icon:'↺', title:'Reflexes', groups:[
    {title:'Deep tendon reflexes', table:{rows:['Biceps','BR','Triceps','Knee','Ankle'], columns:['R','L'], values:['0','1+','2+','3+','4+']}},
    {title:'Pathological reflexes', fields:[['Hoffmann R','choice',['−','+']], ['Hoffmann L','choice',['−','+']], ['Plantar R','choice',['Down','Up']], ['Plantar L','choice',['Down','Up']]]}
  ]},
  { id:'coordination', icon:'⌁', title:'Coordination', groups:[
    {title:'Cerebellar testing', fields:[['Finger–nose','choice',['Normal','R ataxia','L ataxia','Other']], ['Heel–shin','choice',['Normal','R ataxia','L ataxia','Other']], ['Rapid alternating movements','choice',['Normal','Slow','Dysmetric','Other']]]}
  ]},
  { id:'sensation', icon:'✦', title:'Sensation', groups:[
    {title:'Modalities', fields:[['Pinprick','otherChoice',['Normal','Other']], ['Temperature','otherChoice',['Normal','Other']], ['Vibration','otherChoice',['Normal','Other']], ['Joint position fingers','otherChoice',['Normal','Other']], ['Joint position toes','otherChoice',['Normal','Other']], ['Sensory level','text']]}
  ]},
  { id:'gait', icon:'⌁', title:'Gait & other', groups:[
    {title:'Balance and gait', fields:[['Romberg','choice',['Negative','Positive','Unable','Other']], ['Gait','choice',['Normal','Wide based','Spastic','Ataxic','Parkinsonian','High stepping','Antalgic','Other']], ['Tandem','choice',['Normal','Unable','Other']], ['Heel walk','choice',['Normal','Unable','Other']], ['Toe walk','choice',['Normal','Unable','Other']], ['Sit→Stand','choice',['Normal','Uses arms','Other']]]},
    {title:'Other', fields:[['Tremor','text'], ['Myoclonus','text'], ['Dystonia','text'], ['Skin','text'], ['Comments','textarea']]}
  ]}
];
const POWER_ORDER = ['Neck flexion','Neck extension','Shoulder abduction','Shoulder adduction','Elbow flexion','Elbow extension','Wrist flexion','Wrist extension','Finger flexion','Finger abduction','Finger extension','APB','FDI','ADM','Hip flexion','Hip extension','Hip abduction','Hip adduction','Knee flexion','Knee extension','Ankle dorsiflexion','Plantarflexion','Ankle inversion','Ankle eversion'];
const state = JSON.parse(localStorage.getItem('neuro-sheet-v2') || '{}');
const root = document.querySelector('#exam-sections'), nav = document.querySelector('#section-nav'), notePanel = document.querySelector('#note-panel'), noteOutput = document.querySelector('#note-output');
let active = state.active || sections[0].id;
document.querySelector('#exam-date').value = state.date || new Date().toISOString().slice(0,10);
document.querySelector('#patient').value = state.patient || '';
const slug = text => text.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const key = (section,label,suffix='') => `${section.id}-${slug(label)}${suffix}`;
function otherInput(section,label) { const id=key(section,label,'-other'); return `<input class="other-input" data-key="${id}" data-label="${label}" value="${state[id]||''}" placeholder="Describe finding">`; }
function chips(section,label,options,type='choice') { const id=key(section,label); return `<div class="choices">${options.map(option=>`<label class="choice-chip"><input type="radio" name="${id}" value="${option}" data-label="${label}" ${state[id]===option?'checked':''}><span>${option}</span></label>`).join('')}</div>${type==='otherChoice'||options.includes('Other')?`<div class="other-wrap" ${state[id]==='Other'?'':'hidden'}>${otherInput(section,label)}</div>`:''}`; }
function fieldMarkup(section,field) { const [label,type,options] = field; const id=key(section,label);
  if(type==='choice'||type==='otherChoice') return `<div class="field-row"><span class="field-label">${label}</span><div>${chips(section,label,options,type)}</div></div>`;
  if(type==='text'||type==='textarea') { const input=type==='textarea'?`<textarea rows="3" data-key="${id}" data-label="${label}" placeholder="Write finding">${state[id]||''}</textarea>`:`<input data-key="${id}" data-label="${label}" value="${state[id]||''}" placeholder="Write finding">`; return `<div class="field-row"><span class="field-label">${label}</span>${input}</div>`; }
  if(type==='power') return powerMarkup(section,id);
  if(type==='visual') return visualMarkup(section,label);
}
function powerMarkup(section,id) { const view=state[`${id}-view`]||'screen'; const screening=['Shoulder abduction','Shoulder adduction','Elbow flexion','Elbow extension','Wrist flexion','Wrist extension','Finger flexion','Finger abduction','Finger extension','Hip flexion','Hip extension','Knee flexion','Knee extension','Ankle dorsiflexion','Plantarflexion']; const additional=['Neck flexion','Neck extension','APB','FDI','ADM','Hip abduction','Hip adduction','Ankle inversion','Ankle eversion']; const scores=['5','4+','4','4−','3','2','1','0']; const row=(name)=>{const rowId=`${id}-${slug(name)}`, normal=state[`${rowId}-normal`]||false; const select=(side)=>`<select data-power-score data-key="${rowId}-${side}" aria-label="${name} ${side}"><option value=""></option>${scores.map(score=>`<option ${(state[`${rowId}-${side}`]||'')===score?'selected':''}>${score}</option>`).join('')}</select>`; return `<div class="power-row" data-power-row data-name="${name}"><span>${name}</span><button type="button" class="power-normal ${normal?'selected':''}" data-power-normal="${rowId}">5/5 both</button><label>R ${select('r')}</label><label>L ${select('l')}</label></div>`;}; const pane=(name,items,description)=>{const all=items.every(item=>state[`${id}-${slug(item)}-normal`]);return `<div class="power-pane" data-pane="${name}" ${view===name?'':'hidden'}><div class="power-pane-heading"><p>${description}</p><button class="power-all" type="button" data-power-all="${name}">${all?'Clear all':'Mark all 5/5'}</button></div>${items.map(row).join('')}</div>`;}; return `<div class="power-builder"><div class="power-tabs"><button type="button" class="${view==='screen'?'active':''}" data-power-view="${id}" data-view="screen">Screening</button><button type="button" class="${view==='additional'?'active':''}" data-power-view="${id}" data-view="additional">Additional</button><button type="button" class="${view==='custom'?'active':''}" data-power-view="${id}" data-view="custom">Custom</button></div>${pane('screen',screening,'Routine proximal and distal screen')}${pane('additional',additional,'Additional focal neuromuscular testing')}<div class="power-pane" data-pane="custom" ${view==='custom'?'':'hidden'}><textarea rows="3" data-key="${id}-custom" data-label="Power" placeholder="e.g. Neck flexion 4/5; right grip 4+/5">${state[`${id}-custom`]||''}</textarea></div></div>`; }
function visualMarkup(section,label) { const id=key(section,label), selected=state[id]||[]; const cells=['LU','RU','LL','RL']; const eye=(eyeName)=>`<div class="eye-field"><strong>${eyeName} eye</strong><div class="quadrants">${cells.map(cell=>{const value=`${eyeName} ${cell}`;return `<button type="button" class="quadrant ${selected.includes(value)?'selected':''}" data-field="${id}" data-value="${value}" aria-label="${eyeName} eye ${cell}">${cell}</button>`}).join('')}</div></div>`; return `<div class="field-row visual-row"><span class="field-label">${label}</span><div><div class="visual-actions"><button type="button" class="visual-normal ${selected.includes('Normal')?'selected':''}" data-field="${id}" data-normal="true">Normal</button><button type="button" class="visual-other ${selected.includes('Other')?'selected':''}" data-field="${id}" data-other="true">Other</button></div><div class="visual-grid">${eye('Left')}${eye('Right')}</div><div class="other-wrap" ${selected.includes('Other')?'':'hidden'}>${otherInput(section,label)}</div></div></div>`; }
function tableMarkup(section,table,title) { return `<div class="table-wrap"><table class="exam-table"><thead><tr><th>${title}</th>${table.columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row=>`<tr><td>${row}</td>${table.columns.map(col=>{const id=key(section,`${row}-${col}`), value=state[id]||'';return `<td><select data-key="${id}" data-label="${row} ${col}"><option value=""></option>${table.values.map(option=>`<option ${option===value?'selected':''}>${option}</option>`).join('')}</select></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`; }
sections.forEach(section=>{ const el=document.createElement('section'); el.className='exam-section'; el.id=section.id; el.innerHTML=`<div class="section-heading"><span class="section-icon">${section.icon}</span><h2>${section.title}</h2><button class="section-normal" type="button" data-section-normal="${section.id}">Select all normal</button></div>${section.groups.map(g=>`<fieldset class="sheet-group"><legend>${g.title}</legend>${g.fields?g.fields.map(f=>fieldMarkup(section,f)).join(''):tableMarkup(section,g.table,g.title)}</fieldset>`).join('')}`; root.append(el); const tab=document.createElement('button'); tab.type='button';tab.dataset.tab=section.id;tab.textContent=section.title;tab.addEventListener('click',()=>showTab(section.id));nav.append(tab); });
function showTab(id) { active=id; document.querySelectorAll('.exam-section').forEach(el=>el.hidden=el.id!==id); document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===id)); save(); }
function save() { const saved={patient:document.querySelector('#patient').value,date:document.querySelector('#exam-date').value,active}; document.querySelectorAll('input[type=radio]:checked').forEach(el=>saved[el.name]=el.value); document.querySelectorAll('[data-key]').forEach(el=>saved[el.dataset.key]=el.value); document.querySelectorAll('[data-power-normal]').forEach(el=>saved[`${el.dataset.powerNormal}-normal`]=el.classList.contains('selected')); document.querySelectorAll('[data-power-view]').forEach(el=>{if(el.classList.contains('active'))saved[`${el.dataset.powerView}-view`]=el.dataset.view;}); document.querySelectorAll('.visual-row').forEach(row=>{const id=row.querySelector('[data-field]').dataset.field;saved[id]=[...row.querySelectorAll('[data-field].selected')].map(el=>el.dataset.normal?'Normal':el.dataset.other?'Other':el.dataset.value);}); Object.assign(state,saved); localStorage.setItem('neuro-sheet-v2',JSON.stringify(saved)); const chosen=[...document.querySelectorAll('input[type=radio]:checked, [data-key]')].filter(el=>el.matches('input[type=radio]')||el.value.trim()).length + document.querySelectorAll('[data-power-normal].selected, .visual-row [data-field].selected').length; document.querySelector('#progress').textContent=chosen?`${chosen} item${chosen===1?'':'s'} recorded`:'No tests selected yet'; }
function linesFor(section) { const lines=[]; document.querySelectorAll(`#${section.id} input[type=radio]:checked`).forEach(el=>{ const other=el.value==='Other'?document.querySelector(`[data-key="${key(section,el.dataset.label,'-other')}"]`)?.value.trim():''; lines.push(other?`${el.dataset.label}: ${other}`:`${el.dataset.label}: ${el.value}`); }); const powerLines=[]; document.querySelectorAll(`#${section.id} [data-power-row]`).forEach(row=>{const r=row.querySelector('[data-power-score][data-key$="-r"]').value, l=row.querySelector('[data-power-score][data-key$="-l"]').value; if(row.querySelector('[data-power-normal]').classList.contains('selected'))powerLines.push([row.dataset.name,`${row.dataset.name}: 5/5 bilaterally`]); else if(r||l)powerLines.push([row.dataset.name,`${row.dataset.name}: ${r?`R ${r}/5`:''}${r&&l?', ':''}${l?`L ${l}/5`:''}`]);}); powerLines.sort((a,b)=>POWER_ORDER.indexOf(a[0])-POWER_ORDER.indexOf(b[0])); lines.push(...powerLines.map(([,line])=>line)); document.querySelectorAll(`#${section.id} [data-key]:not([data-power-score])`).forEach(el=>{if(el.closest('.other-wrap') && el.closest('.other-wrap').hidden)return; if(el.value.trim())lines.push(`${el.dataset.label}: ${el.value.trim()}`);}); document.querySelectorAll(`#${section.id} .visual-row`).forEach(row=>{const id=row.querySelector('[data-field]').dataset.field, values=state[id]||[]; if(values.includes('Normal'))lines.push('Visual fields: normal'); else {const remaining=values.filter(v=>v!=='Other'); if(remaining.length){const left=new Set(remaining.filter(v=>v.startsWith('Left ')).map(v=>v.slice(5))),right=new Set(remaining.filter(v=>v.startsWith('Right ')).map(v=>v.slice(6))); const homonymous=['LU','LL'].every(x=>left.has(x)&&right.has(x))?'left homonymous hemianopia':['RU','RL'].every(x=>left.has(x)&&right.has(x))?'right homonymous hemianopia':''; const names={LU:'upper-left quadrant',RU:'upper-right quadrant',LL:'lower-left quadrant',RL:'lower-right quadrant'}; lines.push(homonymous?`Visual fields: ${homonymous}`:`Visual fields: ${remaining.map(v=>{const [eye,quadrant]=v.split(' ');return `${eye.toLowerCase()} eye ${names[quadrant]}`;}).join(', ')}`);} const other=document.querySelector(`[data-key="${key(section,'Visual fields','-other')}"]`)?.value.trim();if(other)lines.push(`Visual fields: ${other}`);}}); return [...new Set(lines)]; }
function generateNote() { save(); const header=document.querySelector('#patient').value.trim()?`Neurological examination — ${document.querySelector('#patient').value.trim()}`:'Neurological examination'; const date=document.querySelector('#exam-date').value; const body=sections.map(section=>{const lines=linesFor(section); return lines.length?`- ${section.title}\n${lines.map(line=>`  - ${line}`).join('\n')}`:'';}).filter(Boolean); noteOutput.value=`${header}${date?` (${new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})})`:''}\n\n${body.length?body.join('\n'):'- No examination findings selected.'}`; notePanel.hidden=false; notePanel.scrollIntoView({behavior:'smooth',block:'start'}); }
document.addEventListener('input',save); document.addEventListener('change',event=>{const radio=event.target.closest('input[type=radio]');if(radio){const wrap=radio.closest('.field-row').querySelector('.other-wrap');if(wrap)wrap.hidden=radio.value!=='Other';}const score=event.target.closest('[data-power-score]');if(score&&score.value){score.closest('[data-power-row]').querySelector('[data-power-normal]').classList.remove('selected');}save();});
document.addEventListener('pointerdown',event=>{const chip=event.target.closest('.choice-chip');if(chip){const radio=chip.querySelector('input');radio.dataset.wasChecked=radio.checked?'true':'false';}});
document.addEventListener('click',event=>{const chip=event.target.closest('.choice-chip'),radio=chip?.querySelector('input');if(radio&&radio.dataset.wasChecked==='true'){event.preventDefault();radio.checked=false;const wrap=radio.closest('.field-row').querySelector('.other-wrap');if(wrap)wrap.hidden=true;radio.dataset.wasChecked='false';save();return;}const selectNormal=event.target.closest('[data-section-normal]');if(selectNormal){const section=document.querySelector(`#${selectNormal.dataset.sectionNormal}`);section.querySelectorAll('.choices').forEach(choices=>{const first=choices.querySelector('input[type=radio]');if(first)first.checked=true;});section.querySelectorAll('.other-wrap').forEach(wrap=>wrap.hidden=true);section.querySelectorAll('.visual-row').forEach(row=>{row.querySelectorAll('.quadrant,.visual-other').forEach(el=>el.classList.remove('selected'));row.querySelector('.visual-normal').classList.add('selected');});section.querySelectorAll('.exam-table select').forEach(select=>select.value='2+');section.querySelectorAll('[data-power-normal]').forEach(normal=>{normal.classList.add('selected');normal.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(score=>score.value='');});save();return;}const q=event.target.closest('.quadrant');if(q){const row=q.closest('.visual-row'), normal=row.querySelector('.visual-normal');normal.classList.remove('selected');q.classList.toggle('selected');save();return;} const action=event.target.closest('.visual-normal,.visual-other');if(action){const row=action.closest('.visual-row'); if(action.classList.contains('visual-normal')){row.querySelectorAll('.quadrant,.visual-other').forEach(el=>el.classList.remove('selected'));action.classList.toggle('selected');}else{action.classList.toggle('selected');row.querySelector('.other-wrap').hidden=!action.classList.contains('selected');}save();return;}const view=event.target.closest('[data-power-view]');if(view){const builder=view.closest('.power-builder');builder.querySelectorAll('[data-power-view]').forEach(el=>el.classList.toggle('active',el===view));builder.querySelectorAll('[data-pane]').forEach(el=>el.hidden=el.dataset.pane!==view.dataset.view);save();return;}const all=event.target.closest('[data-power-all]');if(all){const pane=all.closest('.power-pane'), rows=[...pane.querySelectorAll('[data-power-normal]')], activate=!rows.every(row=>row.classList.contains('selected'));rows.forEach(row=>{row.classList.toggle('selected',activate);if(activate)row.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(el=>el.value='');});all.textContent=activate?'Clear all':'Mark all 5/5';save();return;}const normal=event.target.closest('[data-power-normal]');if(normal){normal.classList.toggle('selected');const row=normal.closest('[data-power-row]');if(normal.classList.contains('selected'))row.querySelectorAll('[data-power-score]').forEach(el=>el.value='');save();}});
document.querySelector('#generate-button').addEventListener('click',generateNote); document.querySelector('#clear-button').addEventListener('click',()=>{if(confirm('Clear the examination sheet?')){localStorage.removeItem('neuro-sheet-v2');location.reload();}}); document.querySelector('#copy-button').addEventListener('click',async()=>{await navigator.clipboard.writeText(noteOutput.value);const b=document.querySelector('#copy-button');b.textContent='Copied';setTimeout(()=>b.textContent='Copy note',1300);}); if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');showTab(active);
