const sections = [
  { id:'mental', icon:'◌', title:'Mental status', groups:[
    {title:'Mental status', fields:[
      ['Level of consciousness','otherChoice',['Alert','Drowsy','Other']], ['Orientation','otherChoice',['Orientated','Other']], ['Mental status comments','textarea']
    ]}
  ]},
  { id:'cranial', icon:'◉', title:'Cranial nerves', groups:[
    {title:'Vision and eye movements', fields:[
      ['Fundoscopy','otherChoice',['Normal','Other']], ['Visual acuity','visualAcuity'], ['Visual fields','visual'], ['Pupils','otherChoice',['Equal and reactive','Anisocoria','Sluggish R','Sluggish L','Fixed R','Fixed L','Other']], ['Ptosis','otherChoice',['No','Right','Left','Bilateral','Other']], ['Eye movements','otherChoice',['Full','Other']], ['Pursuits','otherChoice',['Normal','Other']], ['Saccades','otherChoice',['Normal','Other']], ['Nystagmus','otherChoice',['Normal','Other']]
    ]},
    {title:'Face, bulbar and speech', fields:[
      ['Facial sensation','otherChoice',['Normal','Other']], ['Facial movement','otherChoice',['Normal','Other']], ['Hearing','otherChoice',['Symmetric','Reduced R','Reduced L','Other']], ['Palate','otherChoice',['Midline','Asymmetric elevation R','Asymmetric elevation L','Other']], ['Tongue','multiChoice',['Midline','Deviation R','Deviation L','Wasting','Fasciculations','Other']], ['Dysarthria','otherChoice',['No','Other']], ['Aphasia','otherChoice',['No','Other']]
    ]}
  ]},
  { id:'motor', icon:'↗', title:'Motor', groups:[
    {title:'Bulk, tone and drift', fields:[
      ['Bulk UL','text'], ['Bulk LL','text'], ['Tone arms','multiChoice',['Normal','Increased R','Increased L','Reduced R','Reduced L','Other']], ['Tone legs','multiChoice',['Normal','Increased R','Increased L','Reduced R','Reduced L','Other']], ['Pronator drift','choice',['None','Right','Left','Other']], ['Fasciculations','otherChoice',['No','Other']]
    ]},
    {title:'Power (MRC)', fields:[['Power','power']]}
  ]},
  { id:'reflexes', icon:'↺', title:'Reflexes', groups:[
    {title:'Deep tendon reflexes', table:{rows:['Biceps','BR','Triceps','Knee','Ankle'], columns:['R','L'], values:['0','1+','2+','3+','4+']}},
    {title:'Pathological reflexes', fields:[['Hoffmann R','choice',['−','+']], ['Hoffmann L','choice',['−','+']], ['Plantar R','choice',['Down','Up','No response']], ['Plantar L','choice',['Down','Up','No response']]]},
    {title:'Additional reflexes', fields:[['Jaw jerk','choice',['0','1+','2+','3+','4+']], ['Pectoral reflex R','choice',['0','1+','2+','3+','4+']], ['Pectoral reflex L','choice',['0','1+','2+','3+','4+']], ['Adductor reflex R','choice',['0','1+','2+','3+','4+']], ['Adductor reflex L','choice',['0','1+','2+','3+','4+']]]}
  ]},
  { id:'coordination', icon:'⌁', title:'Coordination', groups:[
    {title:'Cerebellar testing', fields:[['Finger–nose','multiChoice',['Normal','R ataxia','L ataxia','Other']], ['Heel–shin','multiChoice',['Normal','R ataxia','L ataxia','Other']], ['Rapid alternating movements','multiChoice',['Normal','Slow R','Slow L','Dysmetric R','Dysmetric L','Other']]]}
  ]},
  { id:'sensation', icon:'✦', title:'Sensation', groups:[
    {title:'Modalities', fields:[['Pinprick','otherChoice',['Normal','Other']], ['Temperature','otherChoice',['Normal','Other']], ['Vibration','otherChoice',['Normal','Other']], ['Joint position fingers','otherChoice',['Normal','Other']], ['Joint position toes','otherChoice',['Normal','Other']], ['Sensory level','text']]}
  ]},
  { id:'gait', icon:'⌁', title:'Gait & other', groups:[
    {title:'Balance and gait', fields:[['Romberg','choice',['Negative','Positive','Unable','Other']], ['Gait','choice',['Normal','Wide based','Spastic','Ataxic','Parkinsonian','High stepping','Antalgic','Other']], ['Tandem','choice',['Normal','Unable','Other']], ['Heel walk','choice',['Normal','Unable','Other']], ['Toe walk','choice',['Normal','Unable','Other']], ['Sit→Stand','choice',['Normal','Uses arms','Other']]]},
    {title:'Other', fields:[['Tremor','text'], ['Myoclonus','text'], ['Dystonia','text'], ['Skin','text'], ['Comments','textarea']]}
  ]}
];
const ROUTINE_NORMALS = {
  mental:{'Level of consciousness':'Alert','Orientation':'Orientated'},
  cranial:{'Fundoscopy':'Normal','Visual fields':'Normal','Pupils':'Equal and reactive','Ptosis':'No','Eye movements':'Full','Nystagmus':'Normal','Facial sensation':'Normal','Facial movement':'Normal','Hearing':'Symmetric','Palate':'Midline','Tongue':'Midline','Dysarthria':'No','Aphasia':'No'},
  motor:{'Tone arms':'Normal','Tone legs':'Normal','Pronator drift':'None'},
  reflexes:{'Biceps R':'2+','Biceps L':'2+','BR R':'2+','BR L':'2+','Triceps R':'2+','Triceps L':'2+','Knee R':'2+','Knee L':'2+','Ankle R':'2+','Ankle L':'2+','Plantar R':'Down','Plantar L':'Down'},
  coordination:{'Finger–nose':'Normal','Heel–shin':'Normal'},
  sensation:{'Pinprick':'Normal','Temperature':'Normal','Vibration':'Normal','Joint position fingers':'Normal','Joint position toes':'Normal'},
  gait:{'Gait':'Normal','Romberg':'Negative','Tandem':'Normal'}
};
const ROUTINE_SECTION_LINES = {
  mental:['Level of consciousness: Alert and orientated'],
  cranial:['Fundoscopy: Normal','Visual fields: Normal','Pupils: Equal and reactive','Ptosis: No','Eye movements: Full','Nystagmus: Normal','Facial sensation: Normal','Facial movement: Normal','Hearing: Symmetric','Palate: Midline','Tongue: Midline','Speech: Normal'],
  motor:['Tone arms: Normal','Tone legs: Normal','Pronator drift: None','Power: 5/5 bilaterally throughout the screened muscle groups (shoulders, elbows, hands, hips, knees, ankles)'],
  reflexes:['Biceps R: 2+   Biceps L: 2+','BR R: 2+   BR L: 2+','Triceps R: 2+   Triceps L: 2+','Knee R: 2+   Knee L: 2+','Ankle R: 2+   Ankle L: 2+','Plantar R: Down   Plantar L: Down'],
  coordination:['Finger–nose: Normal','Heel–shin: Normal'],
  sensation:['Pinprick: Normal','Temperature: Normal','Vibration: Normal','Joint position fingers: Normal','Joint position toes: Normal'],
  gait:['Gait: Normal','Romberg: Negative','Tandem: Normal']
};
const POWER_ORDER = ['Neck flexion','Neck extension','Shoulder abduction','Shoulder adduction','Elbow flexion','Elbow extension','Wrist flexion','Wrist extension','Finger flexion','Finger abduction','Finger extension','APB','FDI','ADM','Hip flexion','Hip extension','Hip abduction','Hip adduction','Knee flexion','Knee extension','Ankle dorsiflexion','Plantarflexion','Ankle inversion','Ankle eversion'];
const WEBSITE_MODE = location.protocol === 'https:';
const state = WEBSITE_MODE ? {} : JSON.parse(localStorage.getItem('neuro-sheet-v2') || '{}');
const root = document.querySelector('#exam-sections'), nav = document.querySelector('#section-nav'), quickRoot = document.querySelector('#quick-screen'), pathwayRoot = document.querySelector('#pathway-screen'), templateRoot = document.querySelector('#template-options'), notePanel = document.querySelector('#note-panel'), noteOutput = document.querySelector('#note-output');
const historyRaw = document.querySelector('#history-raw'), dictateButton = document.querySelector('#dictate-button'), dictationStatus = document.querySelector('#dictation-status');
document.body.classList.toggle('website-mode', WEBSITE_MODE);
let active = state.active || sections[0].id;
let examMode = 'detailed';
let examTemplate = 'detailed';
document.querySelector('#exam-date').value = state.date || new Date().toISOString().slice(0,10);
document.querySelector('#patient').value = state.patient || '';
historyRaw.value = state['history-raw'] || '';
document.querySelector('#exam-mode-state').value = examMode;
document.querySelector('#exam-template-state').value = examTemplate;
const EXAM_TEMPLATES = [['detailed','Detailed assessment','Full neurological examination']];
if(!EXAM_TEMPLATES.some(([id])=>id===examTemplate))examTemplate='detailed';
document.querySelector('#exam-template-state').value = examTemplate;
const TEMPLATE_SECTIONS = {
  detailed:sections.map(section=>section.id)
};
templateRoot.innerHTML=EXAM_TEMPLATES.map(([id,title,description])=>`<button type="button" class="template-option ${examTemplate===id?'active':''}" data-exam-template="${id}"><strong>${title}</strong><span>${description}</span></button>`).join('');
const QUICK_SECTIONS = [
  ['mental','Mental status','Alert'], ['cranial','Cranial nerves','Normal'], ['motor','Motor','Normal'], ['reflexes','Reflexes','Normal'], ['coordination','Coordination','Normal'], ['sensation','Sensation','Normal'], ['gait','Gait','Normal']
];
quickRoot.innerHTML=`<div class="quick-heading"><div><p class="eyebrow">CONFIRM FINDINGS</p><h2>Neurological examination</h2><p>Confirm a normal domain or open only the part that needs documenting.</p></div><button type="button" class="quick-all-normal" data-quick-normal-all>Normal neurological exam</button></div>${QUICK_SECTIONS.map(([id,title,normal])=>{const selected=state[`quick-${id}-normal`]==='true',detail=state[`quick-${id}-other`]||'',expanded=Boolean(detail);return `<article class="quick-card ${selected?'confirmed':''}" data-quick-section="${id}" data-normal-label="${normal}"><div><h2>${title}</h2><p class="quick-status">${detail?'Abnormal finding recorded':selected?`✓ ${normal} confirmed`:'Not recorded'}</p></div><div class="quick-controls"><button type="button" class="quick-normal ${selected?'selected':''}" data-quick-normal="${id}">Mark normal</button><button type="button" class="quick-add" data-quick-add="${id}" aria-expanded="${expanded?'true':'false'}">${expanded?'Hide detail':'Add finding'}</button><input type="hidden" data-key="quick-${id}-normal" value="${selected?'true':''}"><textarea rows="2" data-key="quick-${id}-other" placeholder="Describe the abnormal finding" ${expanded?'':'hidden'}>${detail}</textarea></div></article>`;}).join('')}`;
function syncQuickAllNormalButton(){const cards=[...quickRoot.querySelectorAll('[data-quick-section]')],button=quickRoot.querySelector('[data-quick-normal-all]');if(!button)return;const allSelected=cards.length>0&&cards.every(card=>card.querySelector('[data-key$="-normal"]').value==='true'&&!card.querySelector('textarea').value.trim());button.classList.toggle('selected',allSelected);button.setAttribute('aria-pressed',allSelected?'true':'false');cards.forEach(card=>{const normal=card.querySelector('[data-key$="-normal"]').value==='true',detail=card.querySelector('textarea').value.trim(),status=card.querySelector('.quick-status');card.classList.toggle('confirmed',normal);if(status)status.textContent=detail?'Abnormal finding recorded':normal?`✓ ${card.dataset.normalLabel} confirmed`:'Not recorded';});}
const PATHWAYS = {
  stroke:{title:'Stroke assessment',groups:[
    ['Cortical signs',[['Level of consciousness','otherChoice',['Alert','Drowsy','Other']],['Language','otherChoice',['Normal','Dysphasia','Other']],['Neglect','otherChoice',['No','Yes','Other']],['Visual fields','otherChoice',['Normal','Homonymous hemianopia','Quadrantanopia','Other']]]],
    ['Cranial nerves and speech',[['Facial movement','otherChoice',['Symmetric','Weakness','Other']],['Dysarthria','otherChoice',['No','Yes','Other']],['Gaze','otherChoice',['Midline','Gaze preference','Other']]]],
    ['Motor and coordination',[['Pronator drift','choice',['None','Right','Left','Other']],['Limb power','text'],['Limb ataxia','choice',['None','Right','Left','Other']],['Sensation','otherChoice',['Normal','Hemisensory loss','Other']]]]
  ]},
  movement:{title:'Movement disorder assessment',groups:[
    ['Bradykinesia',[['Finger taps','choice',['Normal','Right impaired','Left impaired','Bilateral impaired','Other']],['Hand opening and closing','choice',['Normal','Right impaired','Left impaired','Bilateral impaired','Other']],['Pronation-supination','choice',['Normal','Right impaired','Left impaired','Bilateral impaired','Other']],['Foot taps','choice',['Normal','Right impaired','Left impaired','Bilateral impaired','Other']]]],
    ['Tone and tremor',[['Rigidity','choice',['Absent','Right','Left','Bilateral','Other']],['Rest tremor','choice',['Absent','Right','Left','Bilateral','Other']],['Postural tremor','choice',['Absent','Right','Left','Bilateral','Other']],['Action tremor','choice',['Absent','Right','Left','Bilateral','Other']]]],
    ['Other involuntary movements',[['Dystonia','otherChoice',['No','Yes','Other']],['Myoclonus','otherChoice',['No','Yes','Other']],['Chorea','otherChoice',['No','Yes','Other']],['Tics','otherChoice',['No','Yes','Other']]]],
    ['Gait and balance',[['Gait','choice',['Normal','Parkinsonian','Ataxic','Spastic','Other']],['Arm swing','choice',['Normal','Reduced right','Reduced left','Reduced bilaterally','Other']],['Turning','choice',['Normal','En bloc','Other']],['Retropulsion','choice',['Negative','Positive','Unable','Other']]]]
  ]},
  neuropathy:{title:'Neuropathy assessment',groups:[
    ['Motor and reflexes',[['Distal power','otherChoice',['Normal','Weakness','Other']],['Reflex pattern','choice',['Normal','Reduced distally','Absent distally','Globally absent','Other']]]],
    ['Sensation',[['Distribution','choice',['Normal','Stocking','Glove','Stocking-glove','Asymmetric','Other']],['Pinprick','otherChoice',['Normal','Reduced','Absent','Other']],['Vibration','otherChoice',['Normal','Reduced distally','Absent distally','Other']],['Joint position','otherChoice',['Normal','Impaired','Other']]]],
    ['Balance and gait',[['Romberg','choice',['Negative','Positive','Unable','Other']],['Gait','choice',['Normal','Sensory ataxic','High stepping','Other']]]]
  ]},
  neuromuscular:{title:'Neuromuscular assessment',groups:[
    ['Ocular and bulbar',[['Ptosis','choice',['No','Right','Left','Bilateral','Other']],['Diplopia','otherChoice',['No','Yes','Other']],['Fatigability','otherChoice',['No','Yes','Other']],['Bulbar symptoms','otherChoice',['No','Yes','Other']]]],
    ['Strength pattern',[['Neck flexion','otherChoice',['Normal','Weak','Other']],['Proximal power','otherChoice',['Normal','Weak','Other']],['Distal power','otherChoice',['Normal','Weak','Other']],['Fasciculations','otherChoice',['No','Yes','Other']]]],
    ['Reflexes and comments',[['Reflexes','choice',['Normal','Reduced','Absent','Brisk','Other']],['Neuromuscular comments','textarea']]]
  ]},
  cognitive:{title:'Cognitive assessment',groups:[
    ['Arousal and attention',[['Level of consciousness','otherChoice',['Alert','Drowsy','Other']],['Orientation','choice',['Intact','Impaired','Other']],['Attention','choice',['Normal','Impaired','Other']]]],
    ['Cognitive domains',[['Language','choice',['Normal','Dysphasia','Other']],['Memory','choice',['Normal','Impaired','Other']],['Executive function','choice',['Normal','Impaired','Other']],['Visuospatial function','choice',['Normal','Impaired','Other']]]],
    ['Summary',[['Cognitive assessment comments','textarea']]]
  ]}
};
const slug = text => text.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const key = (section,label,suffix='') => `${section.id}-${slug(label)}${suffix}`;
function otherInput(section,label) { const id=key(section,label,'-other'); return `<input class="other-input" data-key="${id}" data-label="${label}" value="${state[id]||''}" placeholder="Describe finding">`; }
function chips(section,label,options,type='choice') { const id=key(section,label), multi=type==='multiChoice', selected=multi?(Array.isArray(state[id])?state[id]:[]):[]; return `<div class="choices">${options.map(option=>`<label class="choice-chip"><input type="${multi?'checkbox':'radio'}" ${multi?`data-multi-key="${id}"`:`name="${id}"`} value="${option}" data-label="${label}" ${multi?selected.includes(option)?'checked':'':state[id]===option?'checked':''}><span>${option}</span></label>`).join('')}</div>${type==='otherChoice'||options.includes('Other')?`<div class="other-wrap" ${multi?!selected.includes('Other')?'hidden':'':state[id]!=='Other'?'hidden':''}>${otherInput(section,label)}</div>`:''}`; }
function fieldMarkup(section,field) { const [label,type,options] = field; const id=key(section,label);
  if(type==='choice'||type==='otherChoice'||type==='multiChoice') return `<div class="field-row"><span class="field-label">${label}</span><div>${chips(section,label,options,type)}</div></div>`;
  if(type==='pair') return `<div class="field-row"><span class="field-label">${label}</span><div class="inline-inputs">${options.map(side=>`<label>${side}<input data-key="${id}-${side.toLowerCase()}" data-label="${label} ${side}" value="${state[`${id}-${side.toLowerCase()}`]||''}" placeholder="e.g. 6/6"></label>`).join('')}</div></div>`;
  if(type==='visualAcuity') return visualAcuityMarkup(section,label);
  if(type==='sensoryDrawing') return sensoryDrawingMarkup(section,label);
  if(type==='text'||type==='textarea') { const input=type==='textarea'?`<textarea rows="3" data-key="${id}" data-label="${label}" placeholder="Write finding">${state[id]||''}</textarea>`:`<input data-key="${id}" data-label="${label}" value="${state[id]||''}" placeholder="Write finding">`; return `<div class="field-row"><span class="field-label">${label}</span>${input}</div>`; }
  if(type==='power') return powerMarkup(section,id);
  if(type==='visual') return visualMarkup(section,label);
}
function powerMarkup(section,id) { const view=state[`${id}-view`]||'screen'; const screening=['Shoulder abduction','Shoulder adduction','Elbow flexion','Elbow extension','Wrist flexion','Wrist extension','Finger flexion','Finger abduction','Finger extension','Hip flexion','Hip extension','Knee flexion','Knee extension','Ankle dorsiflexion','Plantarflexion']; const additional=['Neck flexion','Neck extension','APB','FDI','ADM','Hip abduction','Hip adduction','Ankle inversion','Ankle eversion']; const scores=['5','4+','4','4−','3','2','1','0']; const row=(name)=>{const rowId=`${id}-${slug(name)}`, normal=state[`${rowId}-normal`]||false; const select=(side)=>`<select data-power-score data-key="${rowId}-${side}" aria-label="${name} ${side}"><option value=""></option>${scores.map(score=>`<option ${(state[`${rowId}-${side}`]||'')===score?'selected':''}>${score}</option>`).join('')}</select>`; return `<div class="power-row" data-power-row data-name="${name}"><span>${name}</span><button type="button" class="power-normal ${normal?'selected':''}" data-power-normal="${rowId}">5/5 both</button><label>R ${select('r')}</label><label>L ${select('l')}</label></div>`;}; const pane=(name,items,description)=>{const all=items.every(item=>state[`${id}-${slug(item)}-normal`]);return `<div class="power-pane" data-pane="${name}" ${view===name?'':'hidden'}><div class="power-pane-heading"><p>${description}</p><button class="power-all" type="button" data-power-all="${name}">${all?'Clear all':'Mark all 5/5'}</button></div>${items.map(row).join('')}</div>`;}; return `<div class="power-builder"><div class="power-tabs"><button type="button" class="${view==='screen'?'active':''}" data-power-view="${id}" data-view="screen">Screening</button><button type="button" class="${view==='additional'?'active':''}" data-power-view="${id}" data-view="additional">Additional</button><button type="button" class="${view==='custom'?'active':''}" data-power-view="${id}" data-view="custom">Custom</button></div>${pane('screen',screening,'Routine proximal and distal screen')}${pane('additional',additional,'Additional focal neuromuscular testing')}<div class="power-pane" data-pane="custom" ${view==='custom'?'':'hidden'}><textarea rows="3" data-key="${id}-custom" data-label="Power" placeholder="e.g. Neck flexion 4/5; right grip 4+/5">${state[`${id}-custom`]||''}</textarea></div></div>`; }
function visualMarkup(section,label) { const id=key(section,label), selected=state[id]||[]; const cells=['LU','RU','LL','RL']; const eye=(eyeName,abbreviation)=>`<div class="eye-field"><strong>${abbreviation}</strong><div class="visual-field-circle" role="group" aria-label="${eyeName} eye visual field">${cells.map(cell=>{const value=`${eyeName} ${cell}`;return `<button type="button" class="quadrant ${selected.includes(value)?'selected':''}" data-field="${id}" data-value="${value}" aria-label="${eyeName} eye ${cell} visual field"></button>`}).join('')}</div></div>`; return `<div class="field-row visual-row"><span class="field-label">${label}</span><div><div class="visual-actions"><button type="button" class="visual-normal ${selected.includes('Normal')?'selected':''}" data-field="${id}" data-normal="true">Normal</button><button type="button" class="visual-other ${selected.includes('Other')?'selected':''}" data-field="${id}" data-other="true">Other</button></div><div class="visual-grid">${eye('Left','LE')}${eye('Right','RE')}</div><div class="other-wrap" ${selected.includes('Other')?'':'hidden'}>${otherInput(section,label)}</div></div></div>`; }
function visualAcuityMarkup(section,label) { const id=key(section,label), glasses=state[`${id}-glasses`]==='true'; const eye=side=>`<label>${side}<input data-key="${id}-${side.toLowerCase()}" data-label="${label} ${side}" value="${state[`${id}-${side.toLowerCase()}`]||''}" placeholder="e.g. 6/12"><small>Pinhole</small><input data-key="${id}-${side.toLowerCase()}-pinhole" data-label="${label} ${side} pinhole" value="${state[`${id}-${side.toLowerCase()}-pinhole`]||''}" placeholder="e.g. 6/6"></label>`; return `<div class="field-row visual-acuity-row"><span class="field-label">${label}</span><div><div class="visual-acuity-inputs">${eye('R')}${eye('L')}</div><button type="button" class="glasses-button ${glasses?'selected':''}" data-visual-glasses="${id}">Glasses used</button><input type="hidden" data-key="${id}-glasses" value="${glasses?'true':''}"></div></div>`; }
const SENSORY_FINDINGS=['Reduced','Absent','Altered','Hyperalgesia'];
const SENSORY_MODALITIES=['Pinprick','Temperature'];
function sensoryMapData(value) { try { const parsed=JSON.parse(value||'{}'); return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{}; } catch { return {}; } }
function sensoryMapMarkup(section,label) { const id=key(section,label), selected=sensoryMapData(state[id]); const regions=[['face','Face',75,26,11,12],['chest','Chest / abdomen',75,57,19,24],['right-arm','Right arm',43,57,7,21],['left-arm','Left arm',107,57,7,21],['right-hand','Right hand',36,82,6,7],['left-hand','Left hand',114,82,6,7],['right-thigh','Right thigh',64,94,8,19],['left-thigh','Left thigh',86,94,8,19],['right-lower-leg','Right lower leg',64,121,7,19],['left-lower-leg','Left lower leg',86,121,7,19],['right-foot','Right foot',62,143,8,6],['left-foot','Left foot',88,143,8,6]]; const figure=view=>`<div class="body-figure"><span>${view}</span><svg viewBox="0 0 150 156" role="group" aria-label="${view} body map"><path class="body-outline" d="M75 12c-9 0-15 7-15 16 0 7 3 11 7 14l-5 12H50l-7 30h10l3-22h6l3 29-10 55h17l3-43 3 43h17L85 91l3-29h6l3 22h10l-7-30H88l-5-12c4-3 7-7 7-14 0-9-6-16-15-16Z"/><g class="body-regions">${regions.map(([region,regionLabel,x,y,w,h])=>{const finding=selected[`${view}-${region}`]||'',displayX=view==='Back'?150-x:x;return `<g tabindex="0" role="button" aria-label="${view} ${regionLabel}${finding?`, ${finding}`:''}" aria-pressed="${finding?'true':'false'}" class="sensory-region ${finding?'selected':''}" data-sensory-region="${view}-${region}" data-sensory-label="${view.toLowerCase()} ${regionLabel.toLowerCase()}" data-sensory-finding="${finding}"><rect x="${displayX-w/2}" y="${y-h/2}" width="${w}" height="${h}" rx="${Math.min(w,h)/2}"/></g>`;}).join('')}</g></svg></div>`; return `<div class="field-row sensory-map-row"><span class="field-label">${label}</span><div class="sensory-map"><p class="sensory-map-help">Choose a finding, then tap each affected region. Tap a marked region again to remove it.</p><div class="sensory-finding-choices">${SENSORY_FINDINGS.map((finding,index)=>`<button type="button" class="sensory-finding ${index===0?'active':''}" data-sensory-finding-choice="${finding}">${finding}</button>`).join('')}</div><div class="body-maps">${figure('Front')}${figure('Back')}</div><input type="hidden" data-key="${id}" data-label="${label}" value="${JSON.stringify(selected).replace(/"/g,'&quot;')}"><input class="sensory-map-detail" data-key="${id}-detail" data-label="Sensory map detail" value="${state[`${id}-detail`]||''}" placeholder="Optional distribution detail, e.g. left T10 sensory level"></div></div>`; }
function sensoryDrawingData(value) { try { const parsed=JSON.parse(value||'[]'); return Array.isArray(parsed)?parsed:[]; } catch { return []; } }
function sensoryDrawingMarkup(section,label) { const id=key(section,label), drawings=sensoryDrawingData(state[id]), view=state[`${id}-view`]||'Front'; const svg=viewName=>`<svg class="sensory-draw-canvas" data-sensory-draw data-view="${viewName}" viewBox="0 0 150 156" aria-label="${viewName} body map — draw the affected area"><path class="body-outline" d="M75 12c-9 0-15 7-15 16 0 7 3 11 7 14l-5 12H50l-7 30h10l3-22h6l3 29-10 55h17l3-43 3 43h17L85 91l3-29h6l3 22h10l-7-30H88l-5-12c4-3 7-7 7-14 0-9-6-16-15-16Z"/><g data-sensory-strokes>${drawings.filter(stroke=>stroke.view===viewName).map(stroke=>`<polyline class="sensory-stroke" points="${stroke.points.map(point=>point.join(',')).join(' ')}"/>`).join('')}</g></svg>`; return `<div class="field-row sensory-map-row"><span class="field-label">${label}</span><div class="sensory-drawing"><p class="sensory-map-help">Choose a finding, then draw or circle the affected area. The note will use an approximate anatomical description.</p><div class="sensory-finding-choices">${SENSORY_FINDINGS.map((finding,index)=>`<button type="button" class="sensory-finding ${index===0?'active':''}" data-sensory-drawing-finding="${finding}">${finding}</button>`).join('')}</div><div class="drawing-view-tabs"><button type="button" class="${view==='Front'?'active':''}" data-sensory-view="Front">Front</button><button type="button" class="${view==='Back'?'active':''}" data-sensory-view="Back">Back</button></div><div class="drawing-stage">${svg(view)}</div><div class="drawing-actions"><button type="button" data-sensory-undo>Undo last mark</button><button type="button" data-sensory-clear>Clear drawing</button></div><input type="hidden" data-key="${id}" data-label="${label}" value="${JSON.stringify(drawings).replace(/"/g,'&quot;')}"><input type="hidden" data-key="${id}-view" value="${view}"><input class="sensory-map-detail" data-key="${id}-detail" data-label="Sensory map detail" value="${state[`${id}-detail`]||''}" placeholder="Optional refinement, e.g. in an L5 distribution"></div></div>`; }
function tableMarkup(section,table,title) { return `<div class="table-wrap"><table class="exam-table"><thead><tr><th>${title}</th>${table.columns.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row=>`<tr><td>${row}</td>${table.columns.map(col=>{const id=key(section,`${row}-${col}`), value=state[id]||'';return `<td><select data-key="${id}" data-label="${row} ${col}"><option value=""></option>${table.values.map(option=>`<option ${option===value?'selected':''}>${option}</option>`).join('')}</select></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`; }
function sensoryDrawingMarkup(section,label) { const id=key(section,label), drawings=sensoryDrawingData(state[id]), svg=view=>`<svg class="sensory-draw-canvas" data-sensory-draw data-view="${view}" viewBox="0 0 150 156" aria-label="${view} body map — draw the affected area"><path class="body-outline" d="M75 12c-9 0-15 7-15 16 0 7 3 11 7 14l-5 12H50l-7 30h10l3-22h6l3 29-10 55h17l3-43 3 43h17L85 91l3-29h6l3 22h10l-7-30H88l-5-12c4-3 7-7 7-14 0-9-6-16-15-16Z"/><g data-sensory-strokes>${drawings.filter(stroke=>stroke.view===view).map(stroke=>`<polyline class="sensory-stroke" points="${stroke.points.map(point=>point.join(',')).join(' ')}"/>`).join('')}</g><text class="body-view-label" x="75" y="154" text-anchor="middle">${view}</text></svg>`; return `<div class="field-row sensory-map-row"><span class="field-label">${label}</span><div class="sensory-drawing"><p class="sensory-map-help">Choose the modality and finding, then draw or circle the affected area. The note uses an approximate anatomical description.</p><div class="sensory-modality-tabs">${SENSORY_MODALITIES.map((modality,index)=>`<button type="button" class="sensory-modality ${index===0?'active':''}" data-sensory-modality="${modality}">${modality}</button>`).join('')}</div><div class="sensory-finding-choices">${SENSORY_FINDINGS.map((finding,index)=>`<button type="button" class="sensory-finding ${index===0?'active':''}" data-sensory-drawing-finding="${finding}">${finding}</button>`).join('')}</div><div class="drawing-stage drawing-stage-dual">${svg('Front')}${svg('Back')}</div><div class="drawing-actions"><button type="button" data-sensory-undo>Undo last mark</button><button type="button" data-sensory-clear>Clear drawing</button></div><input type="hidden" data-key="${id}" data-label="${label}" value="${JSON.stringify(drawings).replace(/"/g,'&quot;')}"><input class="sensory-map-detail" data-key="${id}-detail" data-label="Sensory detail" value="${state[`${id}-detail`]||''}" placeholder="Optional refinement, e.g. in an L5 distribution"></div></div>`; }
sections.forEach(section=>{ const el=document.createElement('section'); el.className='exam-section'; el.id=section.id; el.innerHTML=`<div class="section-heading"><span class="section-icon">${section.icon}</span><div class="section-title"><h2>${section.title}</h2><p class="section-summary" data-section-summary="${section.id}">Not recorded</p></div><button class="section-normal" type="button" data-section-normal="${section.id}">Mark routine normal</button><button class="section-toggle" type="button" data-section-toggle="${section.id}" aria-expanded="false">Add detail</button></div><div class="section-content" data-section-content="${section.id}" hidden>${section.groups.map(g=>`<section class="sheet-group" data-group="${slug(`${section.id}-${g.title}`)}"><div class="group-heading"><h3>${g.title}</h3><button type="button" class="group-normal" data-group-normal title="Applies normal values to the selectable routine findings in this group.">Mark routine normal</button></div>${g.fields?g.fields.map(f=>fieldMarkup(section,f)).join(''):tableMarkup(section,g.table,g.title)}</section>`).join('')}</div>`; root.append(el); const tab=document.createElement('button'); tab.type='button';tab.dataset.tab=section.id;tab.textContent=section.title;tab.addEventListener('click',()=>showTab(section.id));nav.append(tab); });
nav.addEventListener('click',event=>{const tab=event.target.closest('[data-tab]');if(!tab||!window.matchMedia('(min-width: 1000px)').matches)return;setTimeout(()=>document.getElementById(tab.dataset.tab)?.scrollIntoView({behavior:'smooth',block:'start'}));});
function renderPathway(id) { const pathway=PATHWAYS[id];if(!pathway){pathwayRoot.innerHTML='';return;}const pathwaySection={id:`pathway-${id}`};pathwayRoot.innerHTML=`<section id="${pathwaySection.id}" class="exam-section pathway-exam"><div class="section-heading"><span class="section-icon"></span><h2>${pathway.title}</h2><button class="section-normal" type="button" data-section-normal="${pathwaySection.id}">Select all normal</button></div>${pathway.groups.map(([title,fields])=>`<fieldset class="sheet-group"><legend>${title}</legend>${fields.map(field=>fieldMarkup(pathwaySection,field)).join('')}</fieldset>`).join('')}</section>`;}
function showTab(id) { active=id; document.querySelectorAll('.exam-section').forEach(el=>el.hidden=examMode!=='detailed'&&el.id!==id); document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===id)); save(); }
function applyExamTemplate() { const allowed=TEMPLATE_SECTIONS.detailed; document.querySelectorAll('[data-tab]').forEach(button=>button.hidden=!allowed.includes(button.dataset.tab)); if(!allowed.includes(active))active=allowed[0]; if(examMode==='detailed')showTab(active); }
function showExamMode(mode) { examMode=mode; document.body.dataset.examMode=mode; document.querySelector('#exam-mode-state').value=mode; quickRoot.hidden=mode!=='quick'; pathwayRoot.hidden=mode!=='pathway'; document.querySelectorAll('[data-exam-mode]').forEach(button=>button.classList.toggle('active',button.dataset.examMode===mode)); if(mode==='detailed')applyExamTemplate(); save(); }
function updateSectionSummaries(){document.querySelectorAll('.exam-section').forEach(section=>{const summary=section.querySelector('[data-section-summary]');if(!summary)return;const normal=section.querySelector('.section-normal')?.classList.contains('selected');const recorded=[...section.querySelectorAll('input[type=radio]:checked,input[data-multi-key]:checked,select,[data-key],.power-normal.selected,.visual-row [data-field].selected')].filter(el=>el.matches('select')?Boolean(el.value):el.matches('[data-key]')?!el.matches('input[type=hidden]')&&Boolean(el.value.trim()):true).length;summary.textContent=normal?'✓ Normal confirmed':recorded?`${recorded} finding${recorded===1?'':'s'} recorded`:'Not recorded';section.classList.toggle('has-abnormal-detail',!normal&&recorded>0);});}
function save() { const saved={patient:document.querySelector('#patient').value,date:document.querySelector('#exam-date').value,active}; document.querySelectorAll('input[type=radio]:checked').forEach(el=>saved[el.name]=el.value); document.querySelectorAll('[data-multi-key]').forEach(el=>{const id=el.dataset.multiKey;saved[id]??=[];if(el.checked)saved[id].push(el.value);}); document.querySelectorAll('[data-key]').forEach(el=>saved[el.dataset.key]=el.value); document.querySelectorAll('[data-power-normal]').forEach(el=>saved[`${el.dataset.powerNormal}-normal`]=el.classList.contains('selected')); document.querySelectorAll('[data-power-view]').forEach(el=>{if(el.classList.contains('active'))saved[`${el.dataset.powerView}-view`]=el.dataset.view;}); document.querySelectorAll('.visual-row').forEach(row=>{const id=row.querySelector('[data-field]').dataset.field;saved[id]=[...row.querySelectorAll('[data-field].selected')].map(el=>el.dataset.normal?'Normal':el.dataset.other?'Other':el.dataset.value);}); Object.assign(state,saved); if(!WEBSITE_MODE)localStorage.setItem('neuro-sheet-v2',JSON.stringify(saved)); const chosen=[...document.querySelectorAll('input[type=radio]:checked, input[data-multi-key]:checked, [data-key]')].filter(el=>el.matches('input[type=radio],input[data-multi-key]')||el.value.trim()).length + document.querySelectorAll('[data-power-normal].selected, .visual-row [data-field].selected').length; document.querySelector('#progress').textContent=chosen?`${chosen} item${chosen===1?'':'s'} recorded`:'No tests selected yet'; updateSectionSummaries(); }
function escapeHtml(value) { const el=document.createElement('div'); el.textContent=value; return el.innerHTML; }
function visualFieldLines(row) { const id=row.querySelector('[data-field]').dataset.field, values=state[id]||[], lines=[]; if(values.includes('Normal'))lines.push('Visual fields: Normal'); else {const remaining=values.filter(value=>value!=='Other'), left=new Set(remaining.filter(value=>value.startsWith('Left ')).map(value=>value.slice(5))),right=new Set(remaining.filter(value=>value.startsWith('Right ')).map(value=>value.slice(6))), has=(eye,cells)=>cells.every(cell=>eye.has(cell)); let summary=''; if(has(left,['LU','RU','LL','RL']))summary='complete visual field loss in the left eye'; else if(has(right,['LU','RU','LL','RL']))summary='complete visual field loss in the right eye'; else if(has(left,['LU','LL'])&&has(right,['LU','LL']))summary='left homonymous hemianopia'; else if(has(left,['RU','RL'])&&has(right,['RU','RL']))summary='right homonymous hemianopia'; else if(has(left,['LU','LL'])&&has(right,['RU','RL']))summary='bitemporal hemianopia'; else if(has(left,['RU','RL'])&&has(right,['LU','LL']))summary='binasal hemianopia'; else {const quadrants=[['LU','left superior quadrantanopia'],['LL','left inferior quadrantanopia'],['RU','right superior quadrantanopia'],['RL','right inferior quadrantanopia']]; const match=quadrants.find(([cell])=>left.has(cell)&&right.has(cell)); if(match)summary=`${match[1]} (homonymous)`;} if(!summary&&remaining.length){const names={LU:'upper-left quadrant',RU:'upper-right quadrant',LL:'lower-left quadrant',RL:'lower-right quadrant'};summary=remaining.map(value=>{const [eye,quadrant]=value.split(' ');return `${eye.toLowerCase()} eye ${names[quadrant]} defect`;}).join(', ');} if(summary)lines.push(`Visual fields: ${summary}`); const other=row.querySelector('.other-wrap [data-key]')?.value.trim();if(other)lines.push(`Visual fields: ${other}`);} return lines; }
function powerFieldLines(builder) { const entries=[]; builder.querySelectorAll('[data-power-row]').forEach(row=>{const r=row.querySelector('[data-power-score][data-key$="-r"]').value,l=row.querySelector('[data-power-score][data-key$="-l"]').value,normal=row.querySelector('[data-power-normal]').classList.contains('selected')||(r==='5'&&l==='5');if(normal)entries.push({name:row.dataset.name,normal:true,line:`${row.dataset.name}: 5/5 bilaterally`});else if(r||l)entries.push({name:row.dataset.name,normal:false,line:`${row.dataset.name}: ${r?`R ${r}/5`:''}${r&&l?', ':''}${l?`L ${l}/5`:''}`});}); entries.sort((a,b)=>POWER_ORDER.indexOf(a.name)-POWER_ORDER.indexOf(b.name)); const screenNames=[...builder.querySelectorAll('.power-pane[data-pane="screen"] [data-power-row]')].map(row=>row.dataset.name),screenComplete=screenNames.length>0&&entries.length===screenNames.length&&entries.every(entry=>entry.normal)&&screenNames.every(name=>entries.some(entry=>entry.name===name)); const custom=builder.querySelector('textarea[data-key]')?.value.trim();return [...(screenComplete?['Power: 5/5 bilaterally throughout the screening muscle groups.']:entries.map(entry=>entry.line)),...(custom?[`Power: ${custom}`]:[])]; }
function sensoryMapLines(map) { const data=sensoryMapData(map.querySelector('input[type=hidden][data-key]').value), groups={}; map.querySelectorAll('[data-sensory-region]').forEach(region=>{const finding=data[region.dataset.sensoryRegion];if(finding)(groups[finding]??=[]).push(region.dataset.sensoryLabel);}); const lines=Object.entries(groups).map(([finding,regions])=>`Sensory map: ${finding.toLowerCase()} sensation over ${regions.join(', ')}`); const detail=map.querySelector('.sensory-map-detail').value.trim();if(detail)lines.push(`Sensory map: ${detail}`);return lines; }
function sensoryDrawingLocation(stroke) { const average=stroke.points.reduce((total,[x,y])=>[total[0]+x,total[1]+y],[0,0]).map(total=>total/stroke.points.length),[x,y]=average, front=stroke.view==='Front', right=front?x<75:x>75, side=right?'right':'left'; if(y<22)return `${front?'anterior':'posterior'} forehead`; if(y<34)return `${side} cheek`; if(y<43)return `${side} jaw`; if(y<59&&Math.abs(x-75)<19)return `${front?'anterior chest':'upper back'}`; if(y<87&&Math.abs(x-75)<19)return `${front?'anterior abdomen':'lower back'}`; if(y<67&&Math.abs(x-75)>=19)return `${side} upper arm`; if(y<82&&Math.abs(x-75)>=19)return `${side} forearm`; if(y<91&&Math.abs(x-75)>=19)return `${side} hand`; const legCenter=right?(front?64:86):(front?86:64), outer=right?(front?x<legCenter:x>legCenter):(front?x>legCenter:x<legCenter), surface=outer?'lateral':'medial'; if(y>140)return `${side} ${surface} foot`; if(y>128)return `${side} ${surface} ankle`; if(y>108)return `${side} ${surface} lower leg`; return `${side} thigh`; }
function sensoryDrawingLines(drawing) { const strokes=sensoryDrawingData(drawing.querySelector('input[type=hidden][data-key]').value), groups={}; strokes.forEach(stroke=>{const modality=stroke.modality||'Pinprick',finding=stroke.finding.toLowerCase(),location=sensoryDrawingLocation(stroke),groupKey=`${modality}|${finding}`;(groups[groupKey]??=[]).push(location);}); const lines=Object.entries(groups).map(([key,locations])=>{const [modality,finding]=key.split('|');return `${modality}: ${finding} sensation over ${[...new Set(locations)].join(', ')}`;}); const detail=drawing.querySelector('.sensory-map-detail').value.trim();if(detail)lines.push(detail);return lines; }
function fieldRowLines(row) { const builder=row.querySelector('.power-builder');if(builder)return powerFieldLines(builder);const sensoryDrawing=row.querySelector('.sensory-drawing');if(sensoryDrawing)return sensoryDrawingLines(sensoryDrawing);const sensoryMap=row.querySelector('.sensory-map');if(sensoryMap)return sensoryMapLines(sensoryMap);if(row.classList.contains('visual-row'))return visualFieldLines(row);if(row.classList.contains('visual-acuity-row')){const value=side=>row.querySelector(`[data-key$="-${side}"]`)?.value.trim(), pinhole=side=>row.querySelector(`[data-key$="-${side}-pinhole"]`)?.value.trim(), eye=side=>{const acuity=value(side),ph=pinhole(side);return acuity?`${side.toUpperCase()} ${acuity}${ph?` (pinhole ${ph})`:''}`:'';};const eyes=['r','l'].map(eye).filter(Boolean),glasses=row.querySelector('[data-visual-glasses]')?.classList.contains('selected');return eyes.length?[`Visual acuity: ${eyes.join(', ')}${glasses?' (with glasses)':''}`]:glasses?['Visual acuity assessed with glasses']:[];} const checked=row.querySelector('input[type=radio]:checked');if(checked){const other=checked.value==='Other'?row.querySelector('.other-wrap [data-key]')?.value.trim():'';return [other?`${checked.dataset.label}: ${other}`:`${checked.dataset.label}: ${checked.value}`];} const checkedMulti=[...row.querySelectorAll('input[data-multi-key]:checked')];if(checkedMulti.length){const other=checkedMulti.some(input=>input.value==='Other')?row.querySelector('.other-wrap [data-key]')?.value.trim():'';const values=checkedMulti.filter(input=>input.value!=='Other').map(input=>input.value);if(other)values.push(other);return values.length?[`${checkedMulti[0].dataset.label}: ${values.join(', ')}`]:[];} return [...row.querySelectorAll('[data-key]:not([data-power-score])')].filter(control=>!control.closest('.other-wrap')&&!control.closest('.power-builder')).map(control=>control.value.trim()?`${control.dataset.label}: ${control.value.trim()}`:'').filter(Boolean); }
function linesFor(section) { if(examMode==='quick'){const card=document.querySelector(`[data-quick-section="${section.id}"]`);if(!card)return [];const normal=card.querySelector('[data-key$="-normal"]').value==='true',other=card.querySelector('textarea').value.trim();return other?[other]:normal?[card.dataset.normalLabel]:[];} const sectionElement=document.querySelector(`#${section.id}`);if(sectionElement?.querySelector('.section-normal')?.classList.contains('selected')&&ROUTINE_SECTION_LINES[section.id])return ROUTINE_SECTION_LINES[section.id]; const lines=[]; document.querySelectorAll(`#${section.id} .sheet-group`).forEach(group=>{[...group.children].forEach(child=>{if(child.classList.contains('field-row'))lines.push(...fieldRowLines(child));if(child.classList.contains('power-builder'))lines.push(...powerFieldLines(child));if(child.classList.contains('table-wrap'))child.querySelectorAll('select[data-key]').forEach(select=>{if(select.value)lines.push(`${select.dataset.label}: ${select.value}`);});});}); return [...new Set(lines)]; }
function generateBulletNote(header,dateText) { if(examMode==='pathway'){const pathway=PATHWAYS[examTemplate], groups=[...pathwayRoot.querySelectorAll('.sheet-group')].map(group=>{const lines=[...group.children].flatMap(child=>child.classList.contains('field-row')?fieldRowLines(child):[]);return lines.length?`${group.querySelector('legend').textContent}\n${lines.map(line=>`• ${line}`).join('\n')}`:'';}).filter(Boolean);return `${header}${dateText?` (${dateText})`:''}\n\n${pathway.title}\n\n${groups.length?groups.join('\n\n'):'No findings selected.'}`;} const body=sections.map(section=>{const lines=linesFor(section); return lines.length?`${section.title}\n${lines.map(line=>`• ${line}`).join('\n')}`:'';}).filter(Boolean); return `${header}${dateText?` (${dateText})`:''}\n\n${body.length?body.join('\n\n'):'No examination findings selected.'}`; }
function isNormalLine(line) { return /: (normal|no|none|negative|midline|full|equal and reactive|alert|down|2\+|−|5\/5 bilaterally)$/i.test(line); }
function marked(value,abnormal=true) { return abnormal?`**${value}**`:value; }
function sectionProse(title,lines) { if(!lines.length)return ''; const neutral=lines.filter(line=>/^Visual acuity:/.test(line)), assessed=lines.filter(line=>!neutral.includes(line)), abnormal=assessed.filter(line=>!isNormalLine(line)), detail=neutral.length?` ${neutral.join('; ')}.`:''; if(!assessed.length)return `${title}: ${neutral.join('; ')}.`; if(!abnormal.length)return `${title} was normal in the recorded domains.${detail}`; if(abnormal.length<assessed.length)return `${title} was normal apart from ${abnormal.map(line=>marked(line)).join('; ')}.${detail}`; return `${title}: ${abnormal.map(line=>marked(line)).join('; ')}.${detail}`; }
function powerProse() { const builder=document.querySelector('#motor .power-builder'); if(!builder)return ''; const tested=[]; builder.querySelectorAll('[data-power-row]').forEach(row=>{const name=row.dataset.name, normal=row.querySelector('[data-power-normal]').classList.contains('selected'), r=row.querySelector('[data-power-score][data-key$="-r"]').value, l=row.querySelector('[data-power-score][data-key$="-l"]').value; if(normal||r||l)tested.push({name,normal:normal||(r==='5'&&l==='5'),r,l});}); if(!tested.length)return ''; const upper=tested.some(item=>['Shoulder','Elbow','Wrist','Finger','APB','FDI','ADM'].some(part=>item.name.startsWith(part))), lower=tested.some(item=>['Hip','Knee','Ankle','Plantarflexion'].some(part=>item.name.startsWith(part))); const scope=upper&&lower?'Upper and lower limb power':upper?'Upper limb power':lower?'Lower limb power':'Power'; const weak=[]; tested.filter(item=>!item.normal).forEach(item=>{if(item.r&&item.r!=='5')weak.push(`right ${item.name.toLowerCase()} weakness (${item.r}/5)`); if(item.l&&item.l!=='5')weak.push(`left ${item.name.toLowerCase()} weakness (${item.l}/5)`);}); if(!weak.length)return `${scope} was normal in the tested muscle groups.`; const normalCount=tested.filter(item=>item.normal).length; return normalCount?`${scope} was normal apart from ${weak.map(item=>marked(item)).join(' and ')}.`:`${scope} showed ${weak.map(item=>marked(item)).join(' and ')}.`; }
function coordinationProse(lines) { const ataxia=lines.filter(line=>/ataxia/i.test(line)); if(!ataxia.length)return sectionProse('Coordination',lines); const sides=[...new Set(ataxia.map(line=>line.match(/:\s*([RL]) ataxia/i)?.[1]).filter(Boolean))], side=sides.length===2?'bilateral':sides[0]==='R'?'right-sided':sides[0]==='L'?'left-sided':''; const tests=[...new Set(ataxia.map(line=>line.startsWith('Finger–nose')?'finger–nose':line.startsWith('Heel–shin')?'heel–shin':'coordination'))], testText=tests.length===2?'finger–nose and heel–shin':tests.join(' and '); const extras=lines.filter(line=>!ataxia.includes(line)&&!isNormalLine(line)); return `Coordination was abnormal with ${marked(`${side?`${side} `:''}appendicular ataxia on ${testText} testing`)}.${extras.length?` ${extras.map(line=>marked(line)).join('; ')}.`:''}`; }
function proseNote(header,dateText) { const findings=[]; const mental=linesFor(sections[0]); if(mental.length)findings.push(sectionProse('Mental status',mental)); const cranial=linesFor(sections[1]); if(cranial.length)findings.push(sectionProse('Cranial nerve examination',cranial)); const motor=linesFor(sections[2]).filter(line=>!POWER_ORDER.some(name=>line.startsWith(`${name}:`))&&!line.startsWith('Power:')); const motorParts=[sectionProse('Motor examination',motor),powerProse()].filter(Boolean); if(motorParts.length)findings.push(motorParts.join(' ')); const reflexes=linesFor(sections[3]);if(reflexes.length)findings.push(sectionProse('Reflexes',reflexes)); const coordination=linesFor(sections[4]);if(coordination.length)findings.push(coordinationProse(coordination)); ['Sensation','Gait'].forEach((title,index)=>{const lines=linesFor(sections[index+5]);if(lines.length)findings.push(sectionProse(title,lines));}); return `${header}${dateText?` (${dateText})`:''}\n\n${findings.length?findings.join('\n\n'):'No examination findings selected.'}`; }
function previewHtml(markdown) { return escapeHtml(markdown).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>'); }
function historyForNote(){return historyRaw.value.trim();}
function formatNoteStyle(note){const headings=new Map([['presenting complaint','Presenting Complaint'],['history of presenting illness','History of Presenting Illness'],['associated symptoms','Associated Symptoms'],['relevant background','Relevant Background'],['medications and allergies','Medications and Allergies'],['social history','Social History'],['family history','Family History'],['investigations','Investigations'],['impression','Impression'],['plan','Plan']]);return note.trim().split('\n').map(line=>{const trimmed=line.trim(),heading=headings.get(trimmed.replace(/:$/,'').toLowerCase());if(heading)return heading;if(/^[-*•]\s+/.test(trimmed))return `• ${trimmed.replace(/^[-*•]\s+/,'')}`;return trimmed;}).join('\n');}
function splitClinicalNoteForExam(note){
  const lines=note.trim().split('\n');
  const headingIndex=lines.findIndex(line=>/^(assessment\s*(?:\/|&|and)?\s*plan|impression\s*(?:\/|&|and)?\s*plan|impression|plan)\s*:?$/i.test(line.trim()));
  if(headingIndex>=0)return {before:lines.slice(0,headingIndex).join('\n').trim(),after:lines.slice(headingIndex).join('\n').trim()};
  const paragraphs=note.trim().split(/\n\s*\n/);
  let planIndex=paragraphs.findIndex(paragraph=>/^(?:plan\s*(?:is|:)|management\s+plan\s*(?:is|:)|impression\s*(?:is|:)|assessment\s*(?:is|:)|we\s+will\s+(?:arrange|request|start|refer|review))/i.test(paragraph.trim()));
  if(planIndex>0&&/^(?:overall|in summary|impression|assessment)/i.test(paragraphs[planIndex-1].trim()))planIndex-=1;
  if(planIndex>=0)return {before:paragraphs.slice(0,planIndex).join('\n\n').trim(),after:paragraphs.slice(planIndex).join('\n\n').trim()};
  const inlinePlan=/\b(?:plan\s+(?:is|:)|management\s+plan\s+(?:is|:)|we\s+will\s+(?:arrange|request|start|refer|review))/i.exec(note);
  if(!inlinePlan)return {before:note.trim(),after:''};
  const beforePlan=note.slice(0,inlinePlan.index);
  const impressionStarts=[...beforePlan.matchAll(/\b(?:overall,|in\s+summary,|impression\s*(?:is|:)|assessment\s*(?:is|:))/gi)];
  const splitAt=impressionStarts.length?impressionStarts.at(-1).index:inlinePlan.index;
  return {before:note.slice(0,splitAt).trim(),after:note.slice(splitAt).trim()};
}
function setDictationStatus(message){dictationStatus.textContent=message;}
let speechRecognition=null, dictationBase='';
function supportsDictation(){return Boolean(window.SpeechRecognition||window.webkitSpeechRecognition);}
function stopDictation(){if(!speechRecognition)return;speechRecognition.stop();}
function startDictation(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setDictationStatus('Dictation is not available in this browser. You can still type or paste the history.');return;}dictationBase=historyRaw.value.trim();speechRecognition=new Recognition();speechRecognition.continuous=true;speechRecognition.interimResults=true;speechRecognition.lang=navigator.language||'en-GB';speechRecognition.onstart=()=>{dictateButton.classList.add('recording');dictateButton.textContent='Stop dictation';dictateButton.setAttribute('aria-pressed','true');setDictationStatus('Listening… speak naturally.');};speechRecognition.onresult=event=>{let finalText='',interimText='';for(let i=event.resultIndex;i<event.results.length;i++){if(event.results[i].isFinal)finalText+=event.results[i][0].transcript;else interimText+=event.results[i][0].transcript;}if(finalText){dictationBase=`${dictationBase}${dictationBase?' ':''}${finalText.trim()}`;historyRaw.value=dictationBase;save();}setDictationStatus(interimText?`Listening: ${interimText}`:'Listening… speak naturally.');};speechRecognition.onerror=event=>{setDictationStatus(event.error==='not-allowed'?'Microphone access was not allowed.':`Dictation stopped: ${event.error}.`);};speechRecognition.onend=()=>{dictateButton.classList.remove('recording');dictateButton.textContent='Start dictation';dictateButton.setAttribute('aria-pressed','false');if(dictationStatus.textContent.startsWith('Listening'))setDictationStatus('Dictation stopped. Review the captured text.');speechRecognition=null;};speechRecognition.start();}
async function formatHistory(){const history=historyRaw.value.trim();if(!history){setDictationStatus('Add or dictate some clinical information first.');historyRaw.focus();return;}formatHistoryButton.disabled=true;formatHistoryButton.textContent='Structuring…';setDictationStatus('Organising the clinical note…');try{const response=await fetch('/api/format-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({history})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Unable to structure the clinical note.');historyFormatted.value=payload.history||'';formattedHistoryWrap.hidden=!historyFormatted.value.trim();setDictationStatus('AI-edited note ready — review and edit it.');save();}catch(error){setDictationStatus(error.message||'Unable to structure the clinical note.');}finally{formatHistoryButton.disabled=false;formatHistoryButton.textContent='Structure note with AI';}}
function generateNote() { save(); const header=document.querySelector('#patient').value.trim()?`Neurology note — ${document.querySelector('#patient').value.trim()}`:'Neurology note'; const date=document.querySelector('#exam-date').value, dateText=date?new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'', examNote=generateBulletNote(header,dateText), clinicalNote=formatNoteStyle(historyForNote()), separator=examNote.indexOf('\n\n'), examBody=separator>=0?examNote.slice(separator+2):examNote; if(!clinicalNote){noteOutput.value=examNote;}else{const {before,after}=splitClinicalNoteForExam(clinicalNote), parts=[`${header}${dateText?` (${dateText})`:''}`,before?`Clinical Note\n${before}`:'',`Examination\n\n${examBody}`,after].filter(Boolean);noteOutput.value=parts.join('\n\n');} notePanel.hidden=false; notePanel.scrollIntoView({behavior:'smooth',block:'start'}); }
document.addEventListener('click',event=>{const mode=event.target.closest('[data-exam-mode]');if(mode)showExamMode(mode.dataset.examMode);});
templateRoot.addEventListener('click',event=>{const option=event.target.closest('[data-exam-template]');if(!option)return;examTemplate=option.dataset.examTemplate;document.querySelector('#exam-template-state').value=examTemplate;templateRoot.querySelectorAll('[data-exam-template]').forEach(button=>button.classList.toggle('active',button.dataset.examTemplate===examTemplate));if(examTemplate==='quick')showExamMode('quick');else if(examTemplate==='detailed')showExamMode('detailed');else{renderPathway(examTemplate);showExamMode('pathway');}save();});
document.addEventListener('click',event=>{const toggle=event.target.closest('[data-section-toggle]');if(!toggle)return;const section=document.querySelector(`#${toggle.dataset.sectionToggle}`),content=section?.querySelector('[data-section-content]');if(!content)return;const open=content.hidden;content.hidden=!open;toggle.textContent=open?'Hide detail':'Add detail';toggle.setAttribute('aria-expanded',open?'true':'false');});
quickRoot.addEventListener('click',event=>{const allNormal=event.target.closest('[data-quick-normal-all]');if(allNormal){const clear=allNormal.classList.contains('selected');quickRoot.querySelectorAll('[data-quick-section]').forEach(card=>{const normal=card.querySelector('[data-quick-normal]');normal.classList.toggle('selected',!clear);card.querySelector('[data-key$="-normal"]').value=clear?'':'true';if(!clear)card.querySelector('textarea').value='';card.querySelector('textarea').hidden=true;const add=card.querySelector('[data-quick-add]');add.textContent='Add finding';add.setAttribute('aria-expanded','false');});syncQuickAllNormalButton();save();return;}const add=event.target.closest('[data-quick-add]');if(add){const card=add.closest('[data-quick-section]'),detail=card.querySelector('textarea'),open=detail.hidden;detail.hidden=!open;add.textContent=open?'Hide detail':'Add finding';add.setAttribute('aria-expanded',open?'true':'false');if(open)detail.focus();return;}const normal=event.target.closest('[data-quick-normal]');if(!normal)return;event.preventDefault();const card=normal.closest('[data-quick-section]'),selected=!normal.classList.contains('selected');normal.classList.toggle('selected',selected);card.querySelector('[data-key$="-normal"]').value=selected?'true':'';if(selected){card.querySelector('textarea').value='';card.querySelector('textarea').hidden=true;const add=card.querySelector('[data-quick-add]');add.textContent='Add finding';add.setAttribute('aria-expanded','false');}syncQuickAllNormalButton();save();});
quickRoot.addEventListener('input',event=>{const other=event.target.closest('textarea[data-key$="-other"]');if(!other)return;const card=other.closest('[data-quick-section]'),normal=card.querySelector('[data-quick-normal]');if(other.value.trim()){normal.classList.remove('selected');card.querySelector('[data-key$="-normal"]').value='';}syncQuickAllNormalButton();save();});
function updateSensoryRegion(region) { const map=region.closest('.sensory-map'), hidden=map.querySelector('input[type=hidden][data-key]'), data=sensoryMapData(hidden.value), active=map.querySelector('.sensory-finding.active').dataset.sensoryFindingChoice, key=region.dataset.sensoryRegion; if(data[key]===active)delete data[key];else data[key]=active; hidden.value=JSON.stringify(data); const finding=data[key]||'';region.classList.toggle('selected',Boolean(finding));region.dataset.sensoryFinding=finding;region.setAttribute('aria-pressed',finding?'true':'false');region.setAttribute('aria-label',`${region.dataset.sensoryLabel}${finding?`, ${finding}`:''}`);save(); }
document.addEventListener('click',event=>{const choice=event.target.closest('[data-sensory-finding-choice]');if(choice){const map=choice.closest('.sensory-map');map.querySelectorAll('[data-sensory-finding-choice]').forEach(button=>button.classList.toggle('active',button===choice));return;}const region=event.target.closest('[data-sensory-region]');if(region)updateSensoryRegion(region);});
document.addEventListener('keydown',event=>{const region=event.target.closest?.('[data-sensory-region]');if(region&&(event.key==='Enter'||event.key===' ')){event.preventDefault();updateSensoryRegion(region);}});
let activeSensoryStroke=null;
function sensoryPoint(event,canvas) { const point=canvas.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const transformed=point.matrixTransform(canvas.getScreenCTM().inverse());return [Math.max(0,Math.min(150,Math.round(transformed.x*10)/10)),Math.max(0,Math.min(156,Math.round(transformed.y*10)/10))]; }
function saveSensoryDrawing(drawing) { const hidden=drawing.querySelector('input[type=hidden][data-key]:not([data-key$="-view"])');hidden.value=JSON.stringify(sensoryDrawingData(hidden.value));save(); }
function strokeSvg(stroke) { return `<polyline class="sensory-stroke" points="${stroke.points.map(point=>point.join(',')).join(' ')}"/>`; }
document.addEventListener('pointerdown',event=>{const canvas=event.target.closest('[data-sensory-draw]');if(!canvas)return;const drawing=canvas.closest('.sensory-drawing'),finding=drawing.querySelector('[data-sensory-drawing-finding].active')?.dataset.sensoryDrawingFinding,modality=drawing.querySelector('[data-sensory-modality].active')?.dataset.sensoryModality;if(!finding||!modality)return;event.preventDefault();const stroke={view:canvas.dataset.view,modality,finding,points:[sensoryPoint(event,canvas)]};activeSensoryStroke={canvas,drawing,stroke};const mark=document.createElementNS('http://www.w3.org/2000/svg','polyline');mark.classList.add('sensory-stroke');mark.setAttribute('points',stroke.points[0].join(','));canvas.querySelector('[data-sensory-strokes]').append(mark);activeSensoryStroke.mark=mark;canvas.setPointerCapture?.(event.pointerId);});
document.addEventListener('pointermove',event=>{if(!activeSensoryStroke)return;const {canvas,stroke,mark}=activeSensoryStroke;stroke.points.push(sensoryPoint(event,canvas));mark.setAttribute('points',stroke.points.map(point=>point.join(',')).join(' '));});
document.addEventListener('pointerup',event=>{if(!activeSensoryStroke)return;const {drawing,stroke}=activeSensoryStroke;activeSensoryStroke=null;if(stroke.points.length===1)stroke.points.push([stroke.points[0][0]+.4,stroke.points[0][1]+.4]);const hidden=drawing.querySelector('input[type=hidden][data-key]:not([data-key$="-view"])'),strokes=sensoryDrawingData(hidden.value);strokes.push(stroke);hidden.value=JSON.stringify(strokes);save();});
document.addEventListener('click',event=>{const modality=event.target.closest('[data-sensory-modality]');if(modality){const drawing=modality.closest('.sensory-drawing');drawing.querySelectorAll('[data-sensory-modality]').forEach(button=>button.classList.toggle('active',button===modality));return;}const finding=event.target.closest('[data-sensory-drawing-finding]');if(finding){const drawing=finding.closest('.sensory-drawing');drawing.querySelectorAll('[data-sensory-drawing-finding]').forEach(button=>button.classList.toggle('active',button===finding));return;}const drawingAction=event.target.closest('[data-sensory-undo],[data-sensory-clear]');if(drawingAction){const drawing=drawingAction.closest('.sensory-drawing'),hidden=drawing.querySelector('input[type=hidden][data-key]');let strokes=sensoryDrawingData(hidden.value);strokes=drawingAction.hasAttribute('data-sensory-clear')?[]:strokes.slice(0,-1);hidden.value=JSON.stringify(strokes);drawing.querySelectorAll('[data-sensory-draw]').forEach(canvas=>{canvas.querySelector('[data-sensory-strokes]').innerHTML=strokes.filter(stroke=>stroke.view===canvas.dataset.view).map(strokeSvg).join('');});save();}});
function unsetSectionNormal(section){const button=section?.querySelector('.section-normal');if(button){button.classList.remove('selected');button.textContent='Mark routine normal';}}
document.addEventListener('input',event=>{const section=event.target.closest('.exam-section');unsetSectionNormal(section);save();}); document.addEventListener('change',event=>{const section=event.target.closest('.exam-section');unsetSectionNormal(section);const radio=event.target.closest('input[type=radio]');if(radio){const wrap=radio.closest('.field-row').querySelector('.other-wrap');if(wrap)wrap.hidden=radio.value!=='Other';}const multi=event.target.closest('input[data-multi-key]');if(multi){const row=multi.closest('.field-row'),choices=[...row.querySelectorAll('input[data-multi-key]')];if(multi.checked&&multi.value==='Normal')choices.filter(input=>input!==multi).forEach(input=>input.checked=false);else if(multi.checked)choices.filter(input=>input.value==='Normal').forEach(input=>input.checked=false);const wrap=row.querySelector('.other-wrap');if(wrap)wrap.hidden=!row.querySelector('input[data-multi-key][value="Other"]:checked');}const score=event.target.closest('[data-power-score]');if(score&&score.value){score.closest('[data-power-row]').querySelector('[data-power-normal]').classList.remove('selected');}save();});
document.addEventListener('pointerdown',event=>{const chip=event.target.closest('.choice-chip');if(chip){const radio=chip.querySelector('input');radio.dataset.wasChecked=radio.checked?'true':'false';}});
function clearSectionNormal(section){
  section.querySelectorAll('input[type=radio],input[data-multi-key]').forEach(input=>input.checked=false);
  section.querySelectorAll('.other-wrap').forEach(wrap=>wrap.hidden=true);
  section.querySelectorAll('.visual-row').forEach(row=>row.querySelectorAll('.quadrant,.visual-normal,.visual-other').forEach(el=>el.classList.remove('selected')));
  section.querySelectorAll('.exam-table select').forEach(select=>select.value='');
  section.querySelectorAll('[data-power-normal]').forEach(normal=>{normal.classList.remove('selected');normal.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(score=>score.value='');});
  unsetSectionNormal(section);
}
function setSectionNormal(section){
  const defaults=ROUTINE_NORMALS[section.id]||{};
  section.querySelectorAll('input[type=radio],input[data-multi-key]').forEach(input=>input.checked=defaults[input.dataset.label]===input.value);
  section.querySelectorAll('textarea[data-key],input:not([type=hidden])[data-key]').forEach(input=>input.value='');
  section.querySelectorAll('[data-visual-glasses]').forEach(button=>button.classList.remove('selected'));
  section.querySelectorAll('.other-wrap').forEach(wrap=>wrap.hidden=true);
  section.querySelectorAll('.visual-row').forEach(row=>{const normal=row.querySelector('.visual-normal');row.querySelectorAll('.quadrant,.visual-normal,.visual-other').forEach(el=>el.classList.remove('selected'));if(defaults['Visual fields']==='Normal')normal?.classList.add('selected');});
  section.querySelectorAll('.exam-table select').forEach(select=>select.value=defaults[select.dataset.label]||'');
  section.querySelectorAll('[data-power-normal]').forEach(normal=>{const selected=section.id==='motor'&&normal.closest('.power-pane')?.dataset.pane==='screen';normal.classList.toggle('selected',selected);normal.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(score=>score.value='');});
  const button=section.querySelector('.section-normal');if(button){button.classList.add('selected');button.textContent='Clear routine normal';}
}
function scopeHasRecordedFinding(scope){return [...scope.querySelectorAll('input[type=radio]:checked,input[data-multi-key]:checked,select,textarea,input:not([type=hidden])[data-key],.power-normal.selected,.visual-row [data-field].selected')].some(el=>el.matches('select,textarea,input:not([type=hidden])[data-key]')?Boolean(el.value.trim()):true);}
function clearGroupNormal(group){group.querySelectorAll('input[type=radio],input[data-multi-key]').forEach(input=>input.checked=false);group.querySelectorAll('.other-wrap').forEach(wrap=>wrap.hidden=true);group.querySelectorAll('.visual-row').forEach(row=>row.querySelectorAll('.quadrant,.visual-normal,.visual-other').forEach(el=>el.classList.remove('selected')));group.querySelectorAll('.exam-table select').forEach(select=>select.value='');group.querySelectorAll('.power-pane[data-pane="screen"] [data-power-normal]').forEach(normal=>{normal.classList.remove('selected');normal.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(score=>score.value='');});const button=group.querySelector('.group-normal');if(button){button.classList.remove('selected');button.textContent='Mark routine normal';}unsetSectionNormal(group.closest('.exam-section'));}
function setGroupNormal(group){group.querySelectorAll('.choices').forEach(choices=>{const radio=choices.querySelector('input[type=radio]');if(radio)radio.checked=true;const checks=[...choices.querySelectorAll('input[data-multi-key]')];if(checks.length)checks.forEach(check=>check.checked=check.value==='Normal'||(check.dataset.label==='Tongue'&&check.value==='Midline'));});group.querySelectorAll('.other-wrap').forEach(wrap=>wrap.hidden=true);group.querySelectorAll('.visual-row').forEach(row=>{row.querySelectorAll('.quadrant,.visual-other').forEach(el=>el.classList.remove('selected'));row.querySelector('.visual-normal')?.classList.add('selected');});group.querySelectorAll('.exam-table select').forEach(select=>select.value='2+');group.querySelectorAll('.power-pane[data-pane="screen"] [data-power-normal]').forEach(normal=>{normal.classList.add('selected');normal.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(score=>score.value='');});const button=group.querySelector('.group-normal');if(button){button.classList.add('selected');button.textContent='Clear routine normal';}unsetSectionNormal(group.closest('.exam-section'));}
document.addEventListener('click',event=>{const glasses=event.target.closest('[data-visual-glasses]');if(!glasses)return;glasses.classList.toggle('selected');glasses.parentElement.querySelector('[data-key$="-glasses"]').value=glasses.classList.contains('selected')?'true':'';save();});
document.addEventListener('click',event=>{const groupButton=event.target.closest('[data-group-normal]');if(!groupButton)return;const group=groupButton.closest('.sheet-group');if(groupButton.classList.contains('selected'))clearGroupNormal(group);else if(!scopeHasRecordedFinding(group)||confirm('This will replace the findings already recorded in this group. Continue?'))setGroupNormal(group);save();});
document.addEventListener('click',event=>{const chip=event.target.closest('.choice-chip'),radio=chip?.querySelector('input[type=radio]');if(radio&&radio.dataset.wasChecked==='true'){event.preventDefault();radio.checked=false;const wrap=radio.closest('.field-row').querySelector('.other-wrap');if(wrap)wrap.hidden=true;radio.dataset.wasChecked='false';unsetSectionNormal(radio.closest('.exam-section'));save();return;}const selectNormal=event.target.closest('[data-section-normal]');if(selectNormal){const section=document.querySelector(`#${selectNormal.dataset.sectionNormal}`);if(selectNormal.classList.contains('selected'))clearSectionNormal(section);else if(!scopeHasRecordedFinding(section)||confirm('This will replace the findings already recorded in this section. Continue?'))setSectionNormal(section);save();return;}const q=event.target.closest('.quadrant');if(q){const row=q.closest('.visual-row'), normal=row.querySelector('.visual-normal');normal.classList.remove('selected');q.classList.toggle('selected');unsetSectionNormal(row.closest('.exam-section'));save();return;} const action=event.target.closest('.visual-normal,.visual-other');if(action){const row=action.closest('.visual-row'); if(action.classList.contains('visual-normal')){row.querySelectorAll('.quadrant,.visual-other').forEach(el=>el.classList.remove('selected'));action.classList.toggle('selected');}else{action.classList.toggle('selected');row.querySelector('.other-wrap').hidden=!action.classList.contains('selected');}unsetSectionNormal(row.closest('.exam-section'));save();return;}const view=event.target.closest('[data-power-view]');if(view){const builder=view.closest('.power-builder');builder.querySelectorAll('[data-power-view]').forEach(el=>el.classList.toggle('active',el===view));builder.querySelectorAll('[data-pane]').forEach(el=>el.hidden=el.dataset.pane!==view.dataset.view);save();return;}const all=event.target.closest('[data-power-all]');if(all){const pane=all.closest('.power-pane'), rows=[...pane.querySelectorAll('[data-power-normal]')], activate=!rows.every(row=>row.classList.contains('selected'));rows.forEach(row=>{row.classList.toggle('selected',activate);if(activate)row.closest('[data-power-row]').querySelectorAll('[data-power-score]').forEach(el=>el.value='');});all.textContent=activate?'Clear all':'Mark all 5/5';unsetSectionNormal(pane.closest('.exam-section'));save();return;}const normal=event.target.closest('[data-power-normal]');if(normal){normal.classList.toggle('selected');const row=normal.closest('[data-power-row]');if(normal.classList.contains('selected'))row.querySelectorAll('[data-power-score]').forEach(el=>el.value='');unsetSectionNormal(row.closest('.exam-section'));save();}});
document.querySelector('#generate-button').addEventListener('click',generateNote); document.querySelector('#clear-button').addEventListener('click',()=>{if(confirm('Clear the examination sheet?')){localStorage.removeItem('neuro-sheet-v2');location.reload();}}); document.querySelector('#copy-button').addEventListener('click',async()=>{await navigator.clipboard.writeText(noteOutput.value);const b=document.querySelector('#copy-button');b.textContent='Copied';setTimeout(()=>b.textContent='Copy note',1300);}); if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');syncQuickAllNormalButton();if(PATHWAYS[examTemplate]){renderPathway(examTemplate);showExamMode('pathway');}else{showExamMode(examTemplate==='detailed'?'detailed':'quick');showTab(active);}
